### ISSUE TITLE
Questtion about novelty calculation

### ISSUE THREAD

**Issue by Wangchentong** [microsoft/frame-flow#14]
Thanks for you authors share this great work, i wonder how the pdb dataset is curated for the calculation of novelty? do you split each chain in the pdb database or just based on the training single chain or some thing else?

**Comment by jasonkyuyim** [comment]
Hi, we take the whole PDB dataset as instructed in foldseek's documentation. I believe this is all the single sequences. We use the following flags to run novelty calculations.
```
-alignment-type 1 --format-output query,target,alntmscore,lddt --tmscore-threshold 0.0 --exhaustive-search --max-seqs 10000000000
```
